baseURL = 'https://congnghe-one.vercel.app/'
languageCode = "vi-vn"
title = "Công Nghệ & Kinh Tế"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang chủ"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "sports"
    name = "Thể Thao"
    url = "/sports/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "giới thiệu"
    url = "/about/"
    weight = 3